<a href="https://colab.research.google.com/github/vitu1415/trabalho-II-ML/blob/main/trabalho_II.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [70]:
sns.set_theme(style="whitegrid", palette='rocket')

In [71]:
from google.colab import drive
drive.mount('/content/drive')
path = "/content/drive/MyDrive/ColabNotebooks/dataBase"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [72]:
df = pd.read_csv(path + '/A519.csv', delimiter=";")

df.head(10)

,data,hora,pressao,radiacao,temp_inst,pto_orvalho_inst,umid_inst,vento_vel,Unnamed: 8
0,2013-12-03,0,949.3,-3.540,22.3,21.0,92.0,2.3,NaN
1,2013-12-03,100,949.7,-3.540,22.1,20.6,91.0,2.1,NaN
2,2013-12-03,200,949.4,-3.540,22.1,20.0,88.0,1.3,NaN
3,2013-12-03,300,949.1,-3.540,21.9,20.2,90.0,2.3,NaN
4,2013-12-03,400,948.6,-3.540,21.4,19.8,91.0,1.5,NaN
5,2013-12-03,500,947.8,-3.540,21.2,19.8,92.0,2.0,NaN
6,2013-12-03,600,947.3,-3.540,20.8,19.4,92.0,1.8,NaN
7,2013-12-03,700,947.7,-3.540,20.4,19.6,95.0,1.7,NaN
8,2013-12-03,800,948.3,-3.445,20.4,19.7,95.0,1.8,NaN
9,2013-12-03,900,949.2,38.054,20.6,19.8,95.0,1.9,NaN

In [73]:
df_clean = df
df_clean = df_clean.loc[:, ~df_clean.columns.str.contains("^Unnamed")]

In [74]:
df_clean.shape

(83232, 8)

In [75]:
df_clean.isnull().sum()

data                   0
hora                   0
pressao             5279
radiacao            5279
temp_inst           5279
pto_orvalho_inst    5284
umid_inst           5285
vento_vel           5279
dtype: int64

In [76]:
df_clean = df_clean.dropna()

In [77]:
df_clean.shape

(77945, 8)

limpando dados null, que não agregariam na analise

# Transformação das Datas

In [78]:
df_clean["data"] = pd.to_datetime(df_clean["data"])

df_clean["ano"] = df_clean["data"].dt.year
df_clean["mes"] = df_clean["data"].dt.month
df_clean["dia"] = df_clean["data"].dt.day

In [79]:
df_clean["hora"] = df_clean["hora"] // 100

tratamento das horas, estava em HH:MM, assim dividindo por 100, para ter exatamente a hora em especifico

In [80]:
df_clean.drop(columns=["data"], inplace=True)

In [81]:
df_clean.head(10)

,hora,pressao,radiacao,temp_inst,pto_orvalho_inst,umid_inst,vento_vel,ano,mes,dia
0,0,949.3,-3.540,22.3,21.0,92.0,2.3,2013,12,3
1,1,949.7,-3.540,22.1,20.6,91.0,2.1,2013,12,3
2,2,949.4,-3.540,22.1,20.0,88.0,1.3,2013,12,3
3,3,949.1,-3.540,21.9,20.2,90.0,2.3,2013,12,3
4,4,948.6,-3.540,21.4,19.8,91.0,1.5,2013,12,3
5,5,947.8,-3.540,21.2,19.8,92.0,2.0,2013,12,3
6,6,947.3,-3.540,20.8,19.4,92.0,1.8,2013,12,3
7,7,947.7,-3.540,20.4,19.6,95.0,1.7,2013,12,3
8,8,948.3,-3.445,20.4,19.7,95.0,1.8,2013,12,3
9,9,949.2,38.054,20.6,19.8,95.0,1.9,2013,12,3